<?php

namespace Nantarena\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRepository extends EntityRepository
{
    public function findWithTeams($event)
    {
        return $this->createQueryBuilder('t')
            ->leftJoin('t.game', 'g')
            ->addSelect('g')
            ->leftJoin('t.teams', 'te')
            ->addSelect('te')
            ->leftJoin('te.members', 'm')
            ->addSelect('m')
            ->leftJoin('m.user', 'um')
            ->addSelect('um')
            ->where('t.event = :event')
            ->setParameter('event', $event->getId())
            ->getQuery()
            ->getResult();
    }
}
