<?php

namespace Nantarena\PaymentBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Nantarena\EventBundle\Entity\Entry;

use Nantarena\EventBundle\Entity\Event;
use Nantarena\UserBundle\Entity\User;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends EntityRepository
{

}
