<?php

namespace Nantarena\PaymentBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Nantarena\EventBundle\Entity\Entry;

use Nantarena\EventBundle\Entity\Event;
use Nantarena\UserBundle\Entity\User;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function findValidPaymentByEvent(Event $event)
    {
        $qb = $this->createQueryBuilder('p');
        return $qb
            ->join('p.transactions', 't')
            ->addSelect('t')
            ->where('t.event = :event')
            ->andWhere($qb->expr()->eq('p.valid', true))
            ->setParameter('event', $event)
            ->orderBy('p.date', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function findPaymentByEvent(Event $event)
    {
        $qb = $this->createQueryBuilder('p');
        return $qb
            ->join('p.transactions', 't')
            ->addSelect('t')
            ->where('t.event = :event')
            ->setParameter('event', $event)
            ->orderBy('p.date', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
